name: activity_recognition_flutter
description: Activity recognition plugin for Android and iOS. Provides event-based information about activities detected by the phone.
version: 5.0.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.activity_recognition_flutter
        pluginClass: ActivityRecognitionFlutterPlugin
      ios:
        pluginClass: ActivityRecognitionFlutterPlugin
